on: [push, pull_request]

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Git branch name
        id: git-branch-name
        uses: jeffreyguenther/git-branch-name-action@v2
      - name: Echo the branch name
        run: echo "Branch name ${GIT_BRANCH_NAME}"
